version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway/app:/app/app
    depends_on:
      - auth-db
    command: >
      sh -c "python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000"

  auth-db:
    image: postgres:17
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./.db/auth/:/var/lib/postgresql/data
  
  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    env_file:
      - ./runner/.env
    volumes:
      - ./runner/app:/app/app
    depends_on:
      - runner-db
    command: >
      sh -c "python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000"

  runner-db:
    image: postgres:17
    env_file:
      - ./runner/.env
    volumes:
      - ./.db/runner/:/var/lib/postgresql/data
  
#   redis-insight:
#     image: redis/redisinsight:latest
#     container_name: redis_insight
#     restart: always
#     ports:
#       - "5540:5540"
#     user: root  # <--- ADD THIS LINE
#     depends_on:
#       - runner-redis
#     volumes:
#       - ./.db/redis_insight_data:/data

# # Define the volume at the bottom of the file
# volumes:
#   redis_data:
  