apiVersion: v2
name: api-gateway
description: A Helm chart for StatusHawk API Gateway
type: application
version: 0.1.0
appVersion: "0.2.0"

maintainers:
  - name: Bobur Yusupov
sources:
  - https://github.com/bobur-yusupov/statushawk
