apiVersion: v2
name: runner
description: A Helm chart for StatusHawk Runner Service
type: application
version: 0.1.0
appVersion: "1.16.0"

maintainers:
  - name: Bobur Yusupov
sources:
  - https://github.com/bobur-yusupov/statushawk
