apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5433
      targetPort: 5433
  selector:
    app: {{ .Release.Name }}-postgres
