apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "statushawk.fullname" . }}-migrate
  labels:
    {{- include "statushawk.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "statushawk.fullname" . }}-migrate
      labels:
        {{- include "statushawk.labels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "app/manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: {{ include "statushawk.fullname" . }}-config
            - secretRef:
                name: {{ include "statushawk.fullname" . }}-secrets