{{- if .Values.postgresql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "statushawk.fullname" . }}-postgres
  labels:
    {{- include "statushawk.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "statushawk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "statushawk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:{{ .Values.postgresql.image.tag }}"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.postgresPassword }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          {{- if .Values.postgresql.primary.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.postgresql.primary.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "statushawk.fullname" . }}-postgres-pvc
      {{- end }}
{{- end }}
