{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "statushawk.fullname" . }}-redis
  labels:
    {{- include "statushawk.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "statushawk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "statushawk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "redis:{{ .Values.redis.image.tag }}"
          {{- if not .Values.redis.auth.enabled }}
          command: ["redis-server", "--appendonly", "yes"]
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
{{- end }}
