apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statushawk.fullname" . }}-secrets
type: Opaque
stringData:
  # If using internal DB, use the value from values.yaml
  # In prod, you would override this Secret manually
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  {{- end }}
  
  SECRET_KEY: "django-insecure-^jihrnki)62kxf_9m$qv+kt0@ea927lb#%v*ci5&(bybfb^2@m"

  TELEGRAM_BOT_NAME: {{ .Values.telegram.botName | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.token | quote }}
